import { MaterialPreset } from '../../types/cam';

export const MATERIAL_PRESETS: MaterialPreset[] = [
  {
    id: 'mild-steel-1-5',
    name: '1.5mm Mild Steel',
    thickness: '1.5mm (16ga)',
    feedRate: 3200,
    pierceDelay: 0.7,
    kerfWidth: 1.2,
    leadInRadius: 3.5,
    overburnDistance: 3.0,
    smallHoleFeedScale: 60,
  },
  {
    id: 'mild-steel-3-0',
    name: '3.0mm Mild Steel',
    thickness: '3.0mm (1/8")',
    feedRate: 2400,
    pierceDelay: 0.6,
    kerfWidth: 1.4,
    leadInRadius: 4.0,
    overburnDistance: 3.5,
    smallHoleFeedScale: 60,
  },
  {
    id: 'mild-steel-6-0',
    name: '6.0mm Mild Steel',
    thickness: '6.0mm (1/4")',
    feedRate: 1500,
    pierceDelay: 1.0,
    kerfWidth: 1.6,
    leadInRadius: 5.0,
    overburnDistance: 4.0,
    smallHoleFeedScale: 55,
  },
  {
    id: 'aluminum-3-0',
    name: '3.0mm Aluminium',
    thickness: '3.0mm (1/8")',
    feedRate: 2800,
    pierceDelay: 0.4,
    kerfWidth: 1.3,
    leadInRadius: 4.0,
    overburnDistance: 3.0,
    smallHoleFeedScale: 60,
  },
  {
    id: 'sheet-16ga',
    name: '16ga Sheet (1.5mm)',
    thickness: '1.5mm',
    feedRate: 3400,
    pierceDelay: 0.25,
    kerfWidth: 1.1,
    leadInRadius: 3.0,
    overburnDistance: 2.5,
    smallHoleFeedScale: 65,
  },
  {
    id: 'sheet-10ga',
    name: '10ga Sheet (3.4mm)',
    thickness: '3.4mm',
    feedRate: 2200,
    pierceDelay: 0.7,
    kerfWidth: 1.5,
    leadInRadius: 4.5,
    overburnDistance: 3.5,
    smallHoleFeedScale: 60,
  },
];

export const DEFAULT_CAM_PARAMETERS = {
  materialPreset: 'mild-steel-1-5',
  cutFeedRate: 3200,
  pierceDelay: 0.7,
  kerfWidth: 1.2,
  leadInType: 'arc' as const,
  leadInRadius: 3.5,
  leadInSweepAngle: 90,
  leadInStraightLength: 0,
  leadOutLength: 1.5,
  overburnDistance: 3.0,
  smallHoleThreshold: 30.0,
  smallHoleFeedScale: 60,
  datumOrigin: 'BOTTOM_LEFT' as const,
  positioningMode: 'relative' as const,
  includeComments: false,
  disableLaserMode: true,
  spindleSpeed: 1000,
};
